Add test app
wso2/carbon-uuf-common pull request #13
Opened 2016-12-20 12:16 UTC by Shan1024

This commit will add a new app which can be used to test fragments.

2016-12-20 15:07 UTC, this requested changes

2016-12-20 15:07 UTC, this commented on components/pom.xml
> -    <version>1.0.0-SNAPSHOT</version>
Revert all the changes in this file.

2016-12-20 15:07 UTC, this commented on pom.xml
> -<project xmlns="http://maven.apache.org/POM/4.0.0"
Revert this change.

2016-12-20 15:07 UTC, this commented on pom.xml
> -    <version>1.0.0-SNAPSHOT</version>
Revert this change.

2016-12-20 15:07 UTC, this commented on themes/org.wso2.carbon.uuf.common.theme.default/pom.xml
> -<project xmlns="http://maven.apache.org/POM/4.0.0"
Revert all the changes in this file.

2016-12-20 15:07 UTC, this commented on themes/pom.xml
> -<project xmlns="http://maven.apache.org/POM/4.0.0"
Revert all the changes in this file.

2016-12-21 12:36 UTC, this approved these changes

2016-12-21 12:38 UTC, this requested changes

2016-12-21 12:38 UTC, this commented on tests/apps/org.wso2.carbon.uuf.common.test.app/src/main/pages/index.hbs
> +{{fragment "org.wso2.carbon.uuf.common.foundation.uuf-client"}}
Move this line to line no 3 (before #fillZone)

2016-12-22 05:59 UTC, this approved these changes

2017-01-02 06:29 UTC, Kishanthan requested changes

2017-01-02 06:29 UTC, Kishanthan commented on pom.xml
> +        <module>tests</module>
if this is not used for testing purpose (i.e writing test artifacts and samples) then this module should be names as samples

2017-01-02 08:13 UTC, Kishanthan approved these changes

2017-01-02 08:14 UTC, merged